version: "3.9"  

services:
  target:
    build: ./target/
    ports:
      - "8888:3000"
    environment:
      - RAILS_LOG_TO_STDOUT=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/somewhere"]
      interval: 3s
      timeout: 3s
      retries: 10

  scanner:
    build: ./scanner/
    depends_on:
      target:
        condition: service_healthy
