version: "3.9"  

services:
  target:
    build: ./target/
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 10s
      timeout: 3s
      retries: 10

  scanner:
    build: ./scanner/
    depends_on:
      target:
        condition: service_healthy
